apiVersion: v1
kind: Service
metadata:
  labels:
    app: wine-quality-service
  name: wine-quality-service
spec:
  ports:
    - name: predict
      port: 5000
      targetPort: 5000
  selector:
    app: wine-quality-service
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: wine-quality-service
  name: wine-quality-service
spec:
  selector:
    matchLabels:
      app: wine-quality-service
  template:
    metadata:
      labels:
        app: wine-quality-service
    spec:
      containers:
        - image: crealg5u001.azurecr.io/wine_quality_service
          imagePullPolicy: Always
          name: wine-quality-service
          ports:
            - containerPort: 5000
