variables:
  curated_dataset_table:
    default: hive_metastore.default.credit_default_uci_curated
  experiment_name:
    default: /online-inference-containers-examples-${bundle.target}
  model_name: 
    default: credit-default-uci-custom

resources:
  jobs:
    train_register_model_job:
      name: ${bundle.target}_train_register_model
      job_clusters:
        - job_cluster_key: train_register_model_job_cluster
          new_cluster:
            node_type_id: Standard_D4ads_v5
            num_workers: 1
            spark_version: 14.3.x-cpu-ml-scala2.12
      tasks:
        - task_key: train_model
          job_cluster_key: train_register_model_job_cluster
          notebook_task:
            notebook_path: ../src/01-train-model.ipynb
            base_parameters:
              curated_dataset_table: ${var.curated_dataset_table}
              experiment_name: ${var.experiment_name}
        - task_key: register-model
          job_cluster_key: train_register_model_job_cluster
          depends_on:
            - task_key: train_model
          libraries:
            - pypi:
                package: alibi-detect==0.12.0
          notebook_task:
            notebook_path: ../src/02-register-model.ipynb
            base_parameters:
              curated_dataset_table: ${var.curated_dataset_table}
              experiment_name: ${var.experiment_name}
              model_name: ${var.model_name}
