name: Build

on:
  push:
    branches:
      - development
  pull_request:
    branches:
      - development

jobs:
  build:
    runs-on: ubuntu-latest

    name: Set default shell
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Setup python environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: wine_quality_service_env
          environment-file: service/environment.yaml
          python-version: 3.8
          auto-activate-base: false

      - name: Package model service
        run: |
          # Activate conda  environment
          conda info
          conda activate wine_quality_service_env

          # Configure databricks host
          export MLFLOW_TRACKING_URI=databricks
          export DATABRICKS_HOST="${{ secrets.DATABRICKS_HOST }}"
          export DATABRICKS_TOKEN="${{ secrets.DATABRICKS_TOKEN }}"

          # Get artifact URIs
          PREDICTION_MODEL_ARTIFACT_URI=$(jq --raw-output .prediction_model_artifact_uri service/configuration.json)
          DRIFT_MODEL_ARTIFACT_URI=$(jq --raw-output .drift_model_artifact_uri service/configuration.json)
          OUTLIER_MODEL_ARTIFACT_URI=$(jq --raw-output .outlier_model_artifact_uri service/configuration.json)

          # Download model artifacts from databricks
          PREDICTION_MODEL_ARTIFACT_PATH=$(mlflow artifacts download -u $PREDICTION_MODEL_ARTIFACT_URI)
          DRIFT_MODEL_ARTIFACT_PATH=$(mlflow artifacts download -u $DRIFT_MODEL_ARTIFACT_URI)
          OUTLIER_MODEL_ARTIFACT_PATH=$(mlflow artifacts download -u $OUTLIER_MODEL_ARTIFACT_URI)

          # Package model as webservice with bentoml
          mkdir model_package
          python3 service/package_model_service.py \
            --mlflow-prediction-model-artifiact-path $PREDICTION_MODEL_ARTIFACT_URI \
            --mlflow-drift-model-artifiact-path $DRIFT_MODEL_ARTIFACT_URI \
            --mlflow-outlier-model-artifiact-path $OUTLIER_MODEL_ARTIFACT_URI \
            --package-path model_package

      - name: Build and push image
        uses: azure/CLI@v1
        with:
          azcliversion: 2.30.0
          inlineScript: |
            docker build -t wine_quality_service ./model_package
            az configure --defaults acr=${{ secrets.CONTAINER_REGISTRY_NAME }}
            docker tag wine_quality_service ${{ secrets.CONTAINER_REGISTRY_NAME }}.azurecr.io/wine_quality_service:${{ github.sha }}
            docker push ${{ secrets.CONTAINER_REGISTRY_NAME }}.azurecr.io/wine_quality_service:${{ github.sha }}

      - name: "Upload artifact"
        uses: actions/upload-artifact@v2
        with:
          name: model-package-artifact
          path: model_package
