name: Build-Deploy

on: workflow_dispatch

env:
  PROJECT_NAME: employee-attrition

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - uses: actions/setup-python@v4
        with:
          python-version: 3.8
          cache: pip
      - run: pip install -r service/requirements.txt

      - name: Set databricks host environment variables
        run: |
          echo "MLFLOW_TRACKING_URI=databricks" >> $GITHUB_ENV
          echo "DATABRICKS_HOST=${{ secrets.DATABRICKS_HOST }}" >> $GITHUB_ENV
          echo "DATABRICKS_TOKEN=${{ secrets.DATABRICKS_TOKEN }}" >> $GITHUB_ENV

      - name: Set artifact model environment variables
        run: |
          echo "MODEL_NAME=$(jq --raw-output .model_name service/configuration.json)" >> $GITHUB_ENV
          echo "MODEL_VERSION=$(jq --raw-output .model_version service/configuration.json)" >> $GITHUB_ENV

      - name: Download model artifact
        run: |
          # Get model artifact uri
          MODEL_ARTIFACT_URI=$(curl -X GET -H "Authorization: Bearer ${DATABRICKS_TOKEN}" ${DATABRICKS_HOST}/api/2.0/preview/mlflow/model-versions/get-download-uri -d '{"name": "'"${MODEL_NAME}"'", "version": "'"${MODEL_VERSION}"'"}' | jq ".artifact_uri" --raw-output)

          # Download model artifacts from databricks
          MODEL_ARTIFACT_PATH=$(mlflow artifacts download -u $MODEL_ARTIFACT_URI)

          # Copy model configuration to artifacts directory
          mkdir artifacts
          cp service/configuration.json artifacts/model.json
          cp -R $MODEL_ARTIFACT_PATH service/employee_attrition_model

      - name: ACR login
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.CONTAINER_REGISTRY_NAME }}.azurecr.io
          username: ${{ secrets.CONTAINER_REGISTRY_NAME }}
          password: ${{ secrets.CONTAINER_REGISTRY_PASSWORD }}

      - name: Build and push image
        run: |
          docker build -t ${{ env.PROJECT_NAME }} service
          docker tag ${{ env.PROJECT_NAME }} ${{ secrets.CONTAINER_REGISTRY_NAME }}.azurecr.io/${{ env.PROJECT_NAME }}:${{ github.sha }}
          docker push ${{ secrets.CONTAINER_REGISTRY_NAME }}.azurecr.io/${{ env.PROJECT_NAME }}:${{ github.sha }}

      - name: Update Kubernetes manifest file
        run: |
          export IMAGE_NAME=${{ secrets.CONTAINER_REGISTRY_NAME }}.azurecr.io/${{ env.PROJECT_NAME }}
          export IMAGE_TAG=${{ github.sha }}
          envsubst < manifests/api.yaml > artifacts/manifest.yaml

      - name: Upload model package artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: artifacts

  staging:
    name: Staging
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: Staging

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-artifacts

      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set target Kubernetes cluster
        uses: azure/aks-set-context@v3
        with:
          cluster-name: ${{ secrets.KUBERNETES_NAME }}
          resource-group: ${{ secrets.KUBERNETES_RESOURCE_GROUP }}

      - name: Create image pull secret for ACR
        uses: azure/k8s-create-secret@v4
        with:
          container-registry-url: ${{ secrets.CONTAINER_REGISTRY_NAME }}.azurecr.io
          container-registry-username: ${{ secrets.CONTAINER_REGISTRY_NAME }}
          container-registry-password: ${{ secrets.CONTAINER_REGISTRY_PASSWORD }}
          secret-name: ${{ secrets.CONTAINER_REGISTRY_IMAGE_PULL_SECRET }}
          namespace: default
        id: create-secret

      - name: Deploy to AKS
        uses: azure/k8s-deploy@v4
        with:
          manifests: |
            manifest.yaml
          images: |
            ${{ secrets.CONTAINER_REGISTRY_NAME }}.azurecr.io/${{ env.PROJECT_NAME }}:${{ github.sha }}
          imagepullsecrets: |
            ${{ secrets.CONTAINER_REGISTRY_IMAGE_PULL_SECRET }}
          namespace: default

      - name: Set artifact model environment variables
        run: |
          echo "MODEL_NAME=$(jq --raw-output .model_name model.json)" >> $GITHUB_ENV
          echo "MODEL_VERSION=$(jq --raw-output .model_version model.json)" >> $GITHUB_ENV

      - name: Transition models to staging
        run: |
          curl -i -X POST -H "Authorization: Bearer ${{ secrets.DATABRICKS_TOKEN }}" ${{ secrets.DATABRICKS_HOST }}/api/2.0/preview/mlflow/model-versions/transition-stage -d '{"name": "'"${MODEL_NAME}"'", "version": "'"${MODEL_VERSION}"'", "stage": "Staging", "archive_existing_versions": true}' ;

  production:
    name: Production
    runs-on: ubuntu-latest
    needs: staging
    environment:
      name: Production

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-artifacts

      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set target Kubernetes cluster
        uses: azure/aks-set-context@v3
        with:
          cluster-name: ${{ secrets.KUBERNETES_NAME }}
          resource-group: ${{ secrets.KUBERNETES_RESOURCE_GROUP }}

      - name: Create image pull secret for ACR
        uses: azure/k8s-create-secret@v4
        with:
          container-registry-url: ${{ secrets.CONTAINER_REGISTRY_NAME }}.azurecr.io
          container-registry-username: ${{ secrets.CONTAINER_REGISTRY_NAME }}
          container-registry-password: ${{ secrets.CONTAINER_REGISTRY_PASSWORD }}
          secret-name: ${{ secrets.CONTAINER_REGISTRY_IMAGE_PULL_SECRET }}
          namespace: default
        id: create-secret

      - name: Deploy to AKS
        uses: azure/k8s-deploy@v4
        with:
          manifests: |
            manifest.yaml
          images: |
            ${{ secrets.CONTAINER_REGISTRY_NAME }}.azurecr.io/${{ env.PROJECT_NAME }}:${{ github.sha }}
          imagepullsecrets: |
            ${{ secrets.CONTAINER_REGISTRY_IMAGE_PULL_SECRET }}
          namespace: default

      - name: Set artifact model environment variables
        run: |
          echo "MODEL_NAME=$(jq --raw-output .model_name model.json)" >> $GITHUB_ENV
          echo "MODEL_VERSION=$(jq --raw-output .model_version model.json)" >> $GITHUB_ENV

      - name: Transition models to staging
        run: |
          curl -i -X POST -H "Authorization: Bearer ${{ secrets.DATABRICKS_TOKEN }}" ${{ secrets.DATABRICKS_HOST }}/api/2.0/preview/mlflow/model-versions/transition-stage -d '{"name": "'"${MODEL_NAME}"'", "version": "'"${MODEL_VERSION}"'", "stage": "Production", "archive_existing_versions": true}' ;
